import { z } from "zod";
import { READ_ONLY_TOOL_NAMES } from "@/lib/agent/tools";
import { exceptionCategory } from "@/lib/audit/schema";

/**
 * What the agent did to reach one classification (PRD §15.1).
 *
 * This is an EXPORT of `ai_calls` rows, not a second derivation of them. The
 * screen cannot recompute a reasoning trace the way it recomputes a verdict:
 * a verdict is a function of the fixture and the matcher, but which tools the
 * model chose to call is a fact about one particular run, and the only honest
 * source for it is the row that run wrote. §15.1 is explicit that regenerating
 * it on view is the failure mode — a reader would be shown a different answer
 * from the one the audit trail recorded.
 *
 * It arrives as a committed JSON file rather than a live query for the same
 * reason the settlement fixture does (see `batch.ts`): the page prerenders
 * statically and must not need a database connection to render. `npm run eval
 * -- --write-traces` regenerates it from a real run.
 */
const toolCallSchema = z.object({
  toolName: z.enum(READ_ONLY_TOOL_NAMES),
  input: z.unknown(),
  output: z.unknown(),
});

const traceSchema = z.object({
  /** The payment id, which is what `records.record_id` holds. */
  recordId: z.string().min(1),
  /**
   * Carried onto the screen deliberately. A trace is only meaningful next to
   * the model and prompt that produced it, and showing them means a trace from
   * a mock or a superseded prompt can never be mistaken for the shipped one.
   */
  model: z.string().min(1),
  promptVersion: z.string().min(1),
  verdict: z.enum(["ACCEPTED", "COERCED_UNEXPLAINED", "BLOCKED_WRITE", "FAILED"]),
  category: z.enum(exceptionCategory.enumValues),
  reason: z.string().nullable(),
  toolCalls: z.array(toolCallSchema),
  latencyMs: z.number().int().nonnegative(),
  inputTokens: z.number().int().nonnegative(),
  outputTokens: z.number().int().nonnegative(),
  costMicroUsd: z.number().int().nonnegative(),
});

export type InvestigationToolCall = z.infer<typeof toolCallSchema>;
export type InvestigationTrace = z.infer<typeof traceSchema>;

const fileSchema = z.array(traceSchema);

/**
 * Parse an exported trace file into a lookup by record.
 *
 * Validated rather than cast. The file is generated by a separate command and
 * committed, so it can fall behind the schema between runs; a malformed trace
 * rendered as blanks would put an empty "what the agent did" panel next to a
 * real verdict, which reads as "the agent did nothing" rather than as a broken
 * file.
 */
export function parseTraces(raw: unknown): Map<string, InvestigationTrace> {
  const parsed = fileSchema.safeParse(raw);
  if (!parsed.success) {
    throw new Error(`investigation traces are malformed: ${parsed.error.issues[0]?.message}`);
  }

  const byRecord = new Map<string, InvestigationTrace>();
  for (const trace of parsed.data) {
    // Two traces for one record means two runs were merged into one file. The
    // last would silently win and the panel would show one run's tool calls
    // beside another's verdict.
    if (byRecord.has(trace.recordId)) {
      throw new Error(`investigation traces contain ${trace.recordId} twice`);
    }
    byRecord.set(trace.recordId, trace);
  }
  return byRecord;
}

/** How much of a tool's payload the panel shows before truncating. */
export const TOOL_VALUE_MAX_CHARS = 140;

/**
 * One tool call's input or output, as a single compact line.
 *
 * Truncation is MARKED with an ellipsis rather than silent. A cut-off tool
 * result that looks complete is the same failure as a cut-off reason: a person
 * checking the agent's work would take a partial payload for the whole one and
 * conclude the agent saw less than it did.
 */
export function summariseToolValue(value: unknown, maxChars = TOOL_VALUE_MAX_CHARS): string {
  if (value === undefined) return "—";

  let text: string;
  try {
    text = JSON.stringify(value) ?? "—";
  } catch {
    // A cyclic or otherwise unserialisable payload is a broken trace, not a
    // reason to crash the page a person is using to check a tax figure.
    return "(unserialisable)";
  }

  return text.length <= maxChars ? text : `${text.slice(0, maxChars - 1)}…`;
}
