import { z } from "zod";
import { formatIstDate, formatPeriod } from "@/lib/format/date";
import { formatRupees } from "@/lib/format/money";
import { summariseToolValue, type InvestigationToolCall } from "./trace";

/**
 * One tool call, as two sentences a person can read.
 *
 * The panel used to print the raw payloads: `asked {"amountPaise":149900,...}`
 * and `got {"siblings":[{"entityId":"pay_...","amountPaise":0`. Everything
 * needed to check the agent's work was on screen and none of it was legible,
 * which makes the trace decorative rather than checkable. That matters more
 * here than anywhere else on the page, because the trace is the evidence for
 * the product's central claim: a model chose the category and touched none of
 * the money.
 *
 * There are exactly four tools and they are a closed set enforced by
 * `READ_ONLY_TOOL_NAMES`, so this is four cases and a fallback rather than a
 * general-purpose JSON prettifier.
 */
export type ToolNarration = {
  /** What the agent asked the tool. */
  asked: string;
  /** What came back. */
  found: string;
};

/**
 * The payload shapes, re-declared as parsers rather than cast.
 *
 * A trace file is generated by a separate command and committed, so it can fall
 * behind these tools between runs. A cast would render a stale payload as
 * `undefined` inside a confident sentence; a parse fails cleanly and the raw
 * JSON is shown instead, which is worse to read and impossible to misread.
 */
const priceInput = z.object({ amountPaise: z.number(), feePaise: z.number() });
const priceOutput = z.object({
  cells: z.array(
    z.object({
      cell: z.string(),
      ratePercent: z.number(),
      tiesWithinTolerance: z.boolean(),
    }),
  ),
  tiedCells: z.array(z.string()),
  note: z.string().nullable(),
});

const refundInput = z.object({ paymentId: z.string() });
const refundOutput = z.object({
  refunds: z.array(z.object({ amountPaise: z.number(), settledOn: z.string() })),
  count: z.number(),
});

const siblingInput = z.object({ orderId: z.string() });
const siblingOutput = z.object({ count: z.number(), zeroValueCount: z.number() });

const periodInput = z.object({ settledAtUnixSeconds: z.number() });
const periodOutput = z.object({ period: z.string() });

export function narrateToolCall(call: InvestigationToolCall): ToolNarration {
  switch (call.toolName) {
    case "priceAtPublishedRates":
      return narratePrice(call);
    case "findRefundsForPayment":
      return narrateRefunds(call);
    case "findOrderSiblings":
      return narrateSiblings(call);
    case "resolveFilingPeriod":
      return narratePeriod(call);
  }
}

function narratePrice(call: InvestigationToolCall): ToolNarration {
  const input = priceInput.safeParse(call.input);
  const output = priceOutput.safeParse(call.output);
  if (!input.success || !output.success) return raw(call);

  const asked = `Priced ${formatRupees(input.data.amountPaise)} against every rate Razorpay publishes.`;

  // A note only appears in the one case the tool refuses to price at all:
  // nothing was captured, so every rate "explains" a fee of zero. Saying so is
  // the honest answer, and it is the answer that stops a failed retry reading
  // as a clean match.
  if (output.data.note !== null) return { asked, found: output.data.note };

  const named = output.data.tiedCells.map((cell) => describeCell(cell, output.data.cells));
  if (named.length === 0) {
    return {
      asked,
      found: `No published rate explains the ${formatRupees(input.data.feePaise)} charged.`,
    };
  }
  if (named.length === 1) {
    return { asked, found: `The ${named[0]} rate explains it, within one rupee.` };
  }
  return {
    asked,
    found: `Two rates explain it within one rupee: ${named.join(" and ")}. The fee is ambiguous, not wrong.`,
  };
}

/** `"STANDARD"` → `"2.00% standard"`, using the percentage the tool returned. */
function describeCell(
  cell: string,
  cells: { cell: string; ratePercent: number }[],
): string {
  const found = cells.find((candidate) => candidate.cell === cell);
  const name = cell.toLowerCase();
  return found === undefined ? name : `${found.ratePercent.toFixed(2)}% ${name}`;
}

function narrateRefunds(call: InvestigationToolCall): ToolNarration {
  const input = refundInput.safeParse(call.input);
  const output = refundOutput.safeParse(call.output);
  if (!input.success || !output.success) return raw(call);

  const asked = `Looked for refunds against ${input.data.paymentId}.`;
  if (output.data.count === 0) return { asked, found: "Nothing reversed this payment." };

  const listed = output.data.refunds
    .map((refund) => `${formatRupees(refund.amountPaise)} on ${refund.settledOn}`)
    .join(", ");
  const many = output.data.count === 1 ? "One refund" : `${output.data.count} refunds`;
  return { asked, found: `${many}: ${listed}.` };
}

function narrateSiblings(call: InvestigationToolCall): ToolNarration {
  const input = siblingInput.safeParse(call.input);
  const output = siblingOutput.safeParse(call.output);
  if (!input.success || !output.success) return raw(call);

  const asked = `Looked for other settlement rows on ${input.data.orderId}.`;
  if (output.data.count <= 1) return { asked, found: "That order has this row and no other." };

  const rows = `${output.data.count} rows share that order`;
  const zero =
    output.data.zeroValueCount === 0
      ? "all of them captured something"
      : output.data.zeroValueCount === 1
        ? "one of them captured nothing"
        : `${output.data.zeroValueCount} of them captured nothing`;
  return { asked, found: `${rows}, and ${zero}.` };
}

function narratePeriod(call: InvestigationToolCall): ToolNarration {
  const input = periodInput.safeParse(call.input);
  const output = periodOutput.safeParse(call.output);
  if (!input.success || !output.success) return raw(call);

  return {
    asked: `Resolved which return period a settlement on ${formatIstDate(input.data.settledAtUnixSeconds)} falls into.`,
    found: `${formatPeriod(output.data.period)}.`,
  };
}

/**
 * The payload as it was recorded, when it does not match what this tool returns
 * today. Deliberately ugly: an unreadable line is a signal that the trace file
 * needs regenerating, where a plausible sentence built from missing fields
 * would not be.
 */
function raw(call: InvestigationToolCall): ToolNarration {
  return {
    asked: `Called ${call.toolName} with ${summariseToolValue(call.input)}`,
    found: `Recorded result: ${summariseToolValue(call.output)}`,
  };
}
