import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * The punctuation that reads as machine-written, and the words that give away
 * the occasion rather than the product.
 *
 * Both rules exist because a person told us the page failed them, not because a
 * style guide says so. The em dash is the single most recognisable tell of
 * generated prose, and a page that looks generated undermines a product whose
 * entire argument is that a person can check its working. The occasion words
 * are worse: copy that names the event it was written for stops being about the
 * product the moment the event is over.
 *
 * This is a lint the eye cannot do. The dashes were spread across a dozen files
 * and a search-and-replace would have found the ones already there without
 * stopping the next one, which is the only failure that matters.
 */
const BANNED_PUNCTUATION = [
  { char: "—", name: "an em dash" },
  { char: "–", name: "an en dash" },
];

const BANNED_WORDS = ["demo", "judge", "on stage", "pitch"];

/**
 * Where the reader's words live.
 *
 * `src/app` is every screen, and the two library files below are the ones whose
 * strings are rendered verbatim: the verdict headlines in the detail panel, and
 * the narrated tool calls beside them. Everything else in `src/lib` is either
 * arithmetic or a developer-facing error message.
 */
const COPY_FILES = [
  ...walk("src/app"),
  "src/lib/review/explain.ts",
  "src/lib/review/trace-summary.ts",
  "src/lib/format/record.ts",
];

/**
 * The recorded agent output, which is also copy.
 *
 * This was the hole. Every rule above was enforced against the files we write
 * and none against the files a model wrote, so the page shipped a drafted email
 * whose subject line opened "Timing difference — settlement setl_...". The
 * punctuation is the tell either way, and a reader cannot tell which half of the
 * page a sentence came from, which is the point: the drafts are the product's
 * voice as much as the headings are.
 *
 * Only the punctuation rule applies here. These files also carry the prompts'
 * own vocabulary and are regenerated by a model, so the words that name an
 * occasion are checked where they are authored rather than where they land.
 */
const RECORDED_COPY = [
  "data/synthetic/drafts.json",
  "data/synthetic/explanations.json",
  "data/synthetic/investigations.json",
];

/**
 * The prompts that produce the recorded copy.
 *
 * Held to the same punctuation rule as the output, because a prompt written in
 * dashes teaches the model to answer in dashes. Fixing the recording without
 * fixing the instruction means the next run puts them all back.
 */
/**
 * The five categories as the database spells them, which a reader must never
 * see.
 *
 * `FEE_DEDUCTION` in an answer is the same failure as an em dash in a heading:
 * it tells the reader they are looking at a log rather than at a finding, on
 * the one screen whose argument is that a person can check its working. The
 * plain wording is in `src/lib/labels.ts` and the prompts now hand it to the
 * model, so an occurrence here means a recording predates that instruction.
 *
 * Checked against PROSE ONLY, never the whole file. Every one of these files
 * also carries `"category": "FEE_DEDUCTION"` as a structural field, which is
 * correct and must stay: a test run over the raw JSON would fail on the field
 * and on the sentence alike, and the only way to make it pass would be to break
 * the data. The field is what separates the two, so the field is what it reads.
 */
const BANNED_CONSTANTS = [
  "FEE_DEDUCTION",
  "TIMING",
  "REFUND_NETTED",
  "PARTIAL_PAYMENT",
  "UNEXPLAINED",
];

/** The keys whose values a person reads: answers, reasons, drafts. */
const PROSE_KEYS = ["answer", "reason", "subject", "body", "note", "narration"];

/** Every string held under a prose key, however deeply the file nests it. */
function prose(value: unknown, key: string | null = null): string[] {
  if (typeof value === "string") return key !== null && PROSE_KEYS.includes(key) ? [value] : [];
  if (Array.isArray(value)) return value.flatMap((entry) => prose(entry, key));
  if (value !== null && typeof value === "object") {
    return Object.entries(value).flatMap(([name, entry]) => prose(entry, name));
  }
  return [];
}

const PROMPT_FILES = [
  "src/lib/act/prompt.ts",
  "src/lib/agent/prompt.ts",
  "src/lib/explain/prompt.ts",
];

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return walk(path);
    return path.endsWith(".ts") || path.endsWith(".tsx") ? [path] : [];
  });
}

/**
 * The file with its comments removed.
 *
 * Comments are for whoever maintains this and are not copy, so they are held to
 * the prose rules but not to this one. Stripping them is what makes the test
 * usable: without it every explanatory comment in the codebase would have to be
 * rewritten to keep the page's punctuation clean, and the test would be turned
 * off within a week.
 */
function withoutComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^[ \t]*\/\/.*$/gm, "");
}

describe("on-screen copy", () => {
  it("finds every file it is meant to be checking", () => {
    // A walk that silently returns nothing passes every assertion below it.
    expect(COPY_FILES.length).toBeGreaterThan(10);
    expect(COPY_FILES).toContain("src/app/hero.tsx");
    expect(COPY_FILES).toContain("src/lib/review/explain.ts");
  });

  it("can tell a comment from a string", () => {
    // The stripper is the part of this test most likely to be wrong, and a
    // stripper that removed everything would make the whole file pass.
    const sample = `// a — comment\nconst s = "kept";\n/* block — comment */\nconst t = "also kept";`;
    const stripped = withoutComments(sample);
    expect(stripped).toContain("kept");
    expect(stripped).toContain("also kept");
    expect(stripped).not.toContain("—");
  });

  for (const { char, name } of BANNED_PUNCTUATION) {
    it(`never puts ${name} in front of a reader`, () => {
      const offenders = COPY_FILES.filter((file) =>
        withoutComments(readFileSync(file, "utf8")).includes(char),
      );
      expect(offenders).toEqual([]);
    });
  }

  for (const { char, name } of BANNED_PUNCTUATION) {
    it(`never lets a model put ${name} in front of a reader`, () => {
      const offenders = RECORDED_COPY.filter((file) => readFileSync(file, "utf8").includes(char));
      expect(offenders).toEqual([]);
    });

    it(`never teaches a model to write ${name}`, () => {
      // Comments included on purpose. A prompt file's comments are prose the
      // next person copies from when they extend the instruction.
      const offenders = PROMPT_FILES.filter((file) => readFileSync(file, "utf8").includes(char));
      expect(offenders).toEqual([]);
    });
  }

  it("never shows a reader an unrendered escape sequence", () => {
    // Sixteen drafted emails told the reader an amount of "\\u20b90.00". The
    // model wrote the escape as literal text rather than the character, JSON
    // kept it as literal text because that is what it was, and every layer
    // downstream passed it through faithfully onto the screen. Nothing was
    // wrong with any figure; the sentence around it was unreadable.
    const offenders = RECORDED_COPY.filter((file) => /\\u[0-9a-fA-F]{4}/.test(readFileSync(file, "utf8")));
    expect(offenders).toEqual([]);
  });

  it("can actually see an unrendered escape sequence", () => {
    // A pattern that matched nothing would pass the check above forever.
    expect(/\\u[0-9a-fA-F]{4}/.test(String.raw`amount \u20b90.00`)).toBe(true);
    expect(/\\u[0-9a-fA-F]{4}/.test("amount ₹0.00")).toBe(false);
  });

  it("keeps the drafted emails set out as letters", () => {
    // A blank line between paragraphs is the difference between a letter an
    // accountant can skim and three hundred words in one block. It is also
    // exactly what a careless rewrite removes: a search and replace that works
    // on sentences rather than on lines runs the whole letter together, every
    // figure still correct and the thing unreadable. Nothing else in the gate
    // would have noticed, because no assertion anywhere reads the shape.
    const drafts = JSON.parse(readFileSync("data/synthetic/drafts.json", "utf8")) as {
      draft: { caEmail?: { body?: string } } | null;
    }[];
    const bodies = drafts
      .map((entry) => entry.draft?.caEmail?.body)
      .filter((body): body is string => typeof body === "string");

    expect(bodies.length).toBeGreaterThan(5);
    const runTogether = bodies.filter((body) => !body.includes("\n\n"));
    expect(runTogether).toEqual([]);
  });

  it("is looking at recorded copy that actually exists", () => {
    // A path typo would make both checks above pass on an empty string.
    for (const file of [...RECORDED_COPY, ...PROMPT_FILES]) {
      expect(readFileSync(file, "utf8").length).toBeGreaterThan(200);
    }
  });

  for (const file of RECORDED_COPY) {
    it(`never prints a category constant in the prose of ${file}`, () => {
      const written = prose(JSON.parse(readFileSync(file, "utf8")));
      const offenders = written
        .filter((text) => BANNED_CONSTANTS.some((name) => text.includes(name)))
        .map((text) => text.slice(0, 120));

      expect(offenders).toEqual([]);
    });
  }

  it("reads prose rather than the whole file", () => {
    // The check above passes vacuously if `prose` returns nothing, and it
    // passes wrongly if it returns the structural `category` field too. Both
    // are asserted here, against a shape that carries one of each.
    const sample = { category: "FEE_DEDUCTION", reason: "a fee with no invoice line" };

    expect(prose(sample)).toEqual(["a fee with no invoice line"]);
    expect(prose(JSON.parse(readFileSync(RECORDED_COPY[0], "utf8"))).length).toBeGreaterThan(5);
  });

  for (const word of BANNED_WORDS) {
    it(`never says "${word}" anywhere in the product`, () => {
      // These name the occasion rather than the product. Checked against the
      // whole file, comments included: a comment that says what the screen is
      // for is exactly the kind of thing that gets read out loud later.
      const pattern = new RegExp(`\\b${word.replace(" ", "\\s")}\\b`, "i");
      const offenders = COPY_FILES.filter((file) => pattern.test(readFileSync(file, "utf8")));
      expect(offenders).toEqual([]);
    });
  }
});
