import { Output, generateText, type LanguageModel, type ToolSet } from "ai";
import { MODEL_ID, costMicroUsd, splitUsage, type TokenSplit } from "@/lib/agent/pricing";
import type { aiCalls } from "@/lib/audit/schema";
import { applyActGate, unauthorisedActTools, type GatedDraft } from "./policy";
import { ACT_SYSTEM_PROMPT, recordPrompt, type ActContext, type ActRecord } from "./prompt";
import { ACT_PROMPT_VERSION, actDraftSchema } from "./schema";

/**
 * A ceiling, not a target. Three drafts is more output than either other layer
 * produces, and Claude reasons before answering even at low effort — a ceiling
 * tight enough to "save money" truncates the draft and costs a whole retry.
 */
const MAX_OUTPUT_TOKENS = 4096;

export type ActInput = {
  model: LanguageModel;
  /** The already-classified record to draft for. */
  record: ActRecord;
  /** The period and invoice a CA email has to name. */
  context: ActContext;
  batchId: string;
  /** The `records` row this drafts against. Null for a call not tied to one. */
  recordRowId?: string | null;
  /**
   * Override the tool set. Exists so a test can prove the boundary refuses a
   * tool — production passes nothing, because Act holds none.
   */
  tools?: ToolSet;
  /** Injectable clock, so latency in tests is a fixed number rather than a race. */
  now?: () => number;
};

export type ActResult = GatedDraft & {
  recordId: string;
  /**
   * The `ai_calls` row this call earns — BUILT, NOT WRITTEN, exactly as
   * `investigate()` and `explain()` do it. Keeping it pure means every field
   * can be asserted with no database near the test, and the caller decides
   * whether a draft is recorded at all.
   */
  aiCall: typeof aiCalls.$inferInsert;
};

/**
 * Draft the three next actions for one exception (PRD §9, agent 3).
 *
 * No tools, and no `stopWhen`: there is nothing to look up, so this is a single
 * step. Everything the model needs is rendered into the prompt from the same
 * `recordFigures` the gate checks against, which is what lets the gate be
 * strict about money without being unfair about it.
 *
 * `generateText` + `Output.object`, as both other layers use — not
 * `generateObject`, which takes no `tools` in AI SDK v7 (BUILD-LOG 23). Act
 * passes no tools, but using a different call shape here would mean the one
 * layer whose output goes onto a tax return was generated by a path the other
 * two are not tested through.
 */
export async function act(input: ActInput): Promise<ActResult> {
  const now = input.now ?? Date.now;

  // Checked BEFORE the model is called. Act holds no tools at all, so ANY tool
  // is unauthorised — the boundary is a prohibition rather than an allowlist,
  // which is the strongest form of "drafts only · cannot send" available.
  const blocked = unauthorisedActTools(Object.keys(input.tools ?? {}));
  if (blocked.length > 0) {
    return assemble(input, {
      gated: {
        draft: null,
        resolved: [],
        unresolved: [],
        unbalanced: false,
        misfiled: false,
        misrouted: false,
        verdict: "BLOCKED_WRITE",
      },
      split: { inputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, outputTokens: 0 },
      latencyMs: 0,
      blocked,
    });
  }

  const startedAt = now();

  try {
    const result = await generateText({
      model: input.model,
      output: Output.object({ schema: actDraftSchema }),
      maxOutputTokens: MAX_OUTPUT_TOKENS,
      system: {
        role: "system",
        content: ACT_SYSTEM_PROMPT,
        // Worth it: the bake drafts for every exception back to back, so the
        // prefix is written once and read for a tenth of the price thereafter
        // (PRD §9, "On cost").
        providerOptions: { anthropic: { cacheControl: { type: "ephemeral" } } },
      },
      prompt: recordPrompt(input.record, input.context),
      providerOptions: {
        // The record is decided and its figures are given; drafting is writing
        // rather than reasoning. Effort is what it costs to think.
        anthropic: { effort: "low" },
      },
    });

    return assemble(input, {
      gated: applyActGate(readDraft(result), input.record),
      split: splitUsage(result.usage),
      latencyMs: now() - startedAt,
    });
  } catch (error) {
    // Recovering what the model DID write lets the gate tell "produced a draft
    // the schema rejected" apart from "returned nothing at all". Hand it
    // `undefined` and the two collapse into the one bucket the verdict exists
    // to keep apart.
    return assemble(input, {
      gated: applyActGate(rawFromError(error), input.record),
      split: { inputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, outputTokens: 0 },
      latencyMs: now() - startedAt,
    });
  }
}

/** The model's draft, or nothing if the run never produced one. */
function readDraft(result: { output: unknown }): unknown {
  try {
    return result.output;
  } catch {
    return undefined;
  }
}

/**
 * The invalid draft carried by a rejected `generateText`.
 *
 * A schema mismatch rejects with `NoObjectGeneratedError`, whose cause holds
 * the parsed-but-invalid object. Walks the cause chain, because the depth is an
 * implementation detail of the SDK rather than a contract.
 */
function rawFromError(error: unknown): unknown {
  if (typeof error !== "object" || error === null) return undefined;
  const carrier = error as { value?: unknown; cause?: unknown };
  if (carrier.value !== undefined) return carrier.value;
  if (carrier.cause !== undefined && carrier.cause !== error) return rawFromError(carrier.cause);
  return undefined;
}

function assemble(
  input: ActInput,
  parts: {
    gated: GatedDraft;
    split: TokenSplit;
    latencyMs: number;
    blocked?: string[];
  },
): ActResult {
  const { gated, split, latencyMs, blocked } = parts;

  return {
    ...gated,
    recordId: input.record.recordId,
    aiCall: {
      batchId: input.batchId,
      recordId: input.recordRowId ?? null,
      layer: "ACT",
      model: MODEL_ID,
      promptVersion: ACT_PROMPT_VERSION,
      ...split,
      latencyMs,
      costMicroUsd: costMicroUsd(split),
      verdict: gated.verdict,
      // Act may not classify, so this column stays empty for every row this
      // layer writes. An audit query can therefore prove the boundary held.
      category: null,
      // Act holds no tools, so this is empty by construction rather than
      // because none happened to be called. A non-empty array on an ACT row
      // means the boundary was breached.
      toolCalls: [],
      reason: blocked !== undefined ? `Refused: Act may not hold ${blocked.join(", ")}.` : summary(gated),
    },
  };
}

/**
 * One line for the audit trail, from the draft that was produced.
 *
 * The full draft goes to `actions.draft` when a person confirms it; this column
 * is what an audit query reads, so it records what was drafted rather than
 * repeating the whole email into a second table.
 */
function summary(gated: GatedDraft): string | null {
  if (gated.draft === null) return null;

  const { gstr3bFlag, tallyEntry } = gated.draft;
  return [
    gated.draft.caEmail.subject,
    `GSTR-3B ${gstr3bFlag.action}${gstr3bFlag.line === null ? "" : ` on ${gstr3bFlag.line}`}`,
    `Tally ${tallyEntry.voucherType}, ${tallyEntry.lines.length} lines`,
  ].join(" · ");
}
